### ISSUE TITLE
Stop recording after 2-3 seconds

### ISSUE THREAD

**Issue by wsnnn** [polatolu/POVoiceHUD#1]
On the simulator recording lasts allotted time. On the iPad (iOS 6.1) sometimes spontaneously recording stops after 2-3 seconds. There are suspicions about the lack of space on the device (look in settings - 680 MB free). Used to check the standard project POVoiceHUD. Is there a way to determine the cause of this behavior?

**Comment by polatolu** [comment]
Hello,

In POVoiceHUD.m file's 159th line there is a condition that checks the sound level. If the sound level is low enough near to the silence, it stops recording and commits contents to the file. It also checks for the duration to be at least 3 seconds. 

Maybe sound level from microphone is the issue you are having, you can test by changing sound level until you get the best result.

```
if (([recorder averagePowerForChannel:0] < -60.0) && (recordTime > 3.0)) {
    [self commitRecording];
    return;
}
```

**Comment by wsnnn** [comment]
I left only the check of time. Everything works fine. Thank you very much!
