### ISSUE TITLE
Vector graphic

### ISSUE THREAD

**Issue by fulldecent** [polatolu/POVoiceHUD#2]
Please draw graphics as vector so this will work on retina devices and iPads by automatically scaling.

**Comment by polatolu** [comment]
Do you mean to add an microphone@2x.png to the project? Because all other drawing done by CocoaFramework, the only bitmap is microphone.png. 

Will add the file when I haev time.

Thanks for the feedback.

**Comment by fulldecent** [comment]
Actually I am requesting for the microphone to be drawn as a CoreGraphic. This will allow it to scale up when displayed on the iPad. Currently the smaller bitmap is just stretched

**Comment by polatolu** [comment]
OK, I'll add a code for drawing microphone image as vector when I'm free. If you need it urgently, you can make Pull Request and implement it by yourself.

**Comment by fulldecent** [comment]
Thank you, also I am studying your code and thinking about using some of it in my new project at https://github.com/fulldecent/FDWaveformView

**Comment by fulldecent** [comment]
reference: more specific link https://github.com/fulldecent/FDWaveformView/issues/3
